import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import InputForm from "../components/InputForm";
import Post from "../components/Post";
import PostsContainer from "../components/PostsContainer";
import styles from "../styles/Home.module.css";
import { PostType } from "../types";

const data: Array<PostType> = [
  {
    name: "John Snow",
    text: "Hello world!",
  },
  {
    name: "Gandalf White",
    text: "You shall not pass!!!",
  },
  {
    name: "Lorem Impus",
    text: "Edison bulb retro cloud bread echo park, helvetica stumptown taiyaki taxidermy 90's cronut +1 kinfolk. Single-origin coffee ennui shaman taiyaki vape DIY tote bag drinking vinegar cronut adaptogen squid fanny pack vaporware. Man bun next level coloring book skateboard four loko knausgaard. Kitsch keffiyeh master cleanse direct trade indigo juice before they sold out gentrify plaid gastropub normcore XOXO 90's pickled cindigo jean shorts. Slow-carb next level shoindigoitch ethical authentic, yr scenester sriracha forage franzen organic drinking",
  },
];

const Home: NextPage = () => {
  const [posts, setPosts] = useState(
    data.map((obj, i) => <Post key={i} data={obj} />)
  );

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <InputForm setPosts={setPosts} />
        <PostsContainer>{posts}</PostsContainer>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
